### ISSUE TITLE
Grant WRITE to retailstoremanager

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#63] opened 2016-05-23 07:03 UTC
This will make the scenario more realistic based on our discussion with subject-matter experts.

**Comment by jakepeyser** [comment] 2016-06-29 03:38
Tested and this is working as intended. However, it looks like retail managers can create a shipment going to any retailer. Shouldn't they only have permission to create shipments intended for their store?

**Comment by l2fprod** [comment] 2016-06-29 08:02
@jakepeyser 
this is a check we can add for sure. However before enforcing more business logic in the simulator, we should spend time on defining the end-to-end scenario. All these business rules would become additional code in the simulator that may not bring a lot to our demo.

**Comment by jakepeyser** [comment] 2016-06-29 14:55
So considering the conversation @benrondeau and I had last week on demo flows, this won't be possible from the front end we are building. However, shouldn't this business logic just be the case all around since the Controller API is potentially consumable by other clients?

**Comment by jakepeyser** [comment] 2016-07-05 20:53
@l2fprod @benrondeau thoughts? I cannot think of another business rule that we would need to enforce at the ERP level

**Comment by benrondeau** [comment] 2016-07-05 21:32
Relying on the front end alone to ensure proper business logic is not a good way to go, but I am not sure what amount of effort will be necessary to program this on the back-end. I will try to make it impossible for a retail store manager to order for another store, but this could be hacked (which is unlikely) or errors made that the back-end will accept without question unless there is some logic preventing this.

**Comment by l2fprod** [comment] 2016-07-06 08:38
the "hacking" would only occur for someone using the API and within the context of a demo environment, so basically this means it is intentionally from the developer who created a new demo environment and is using our API. So indeed very unlikely.

Can the shipment really be created only by the one that will receive it? Well it might be that it is the person sending it that will create the shipment instead. This all depends on how we will script our scenarios. We are not building a Logistics SaaS that the main reason I would refrain from putting too much business logic in the simulator. Logic that may be different if we move to another ERP.

**Comment by jakepeyser** [comment] 2016-07-06 16:01
Right, @l2fprod, I guess I am just trying to close any loose ends I can think of. My thought was that retail managers can only create shipments for their store, but supply chain managers can create shipments going to any retailer. However, it is not a priority and like you said may change based on the ERP we use. Business logic like this might be better to revisit in a more holistic fashion once implementation with an ERP is relatively complete. With that being said, closing this issue. _bangs gavel_

**Closed by jakepeyser** 2016-07-06 16:01 UTC
Labels: erp-service, task
