### ISSUE TITLE
Demo Onboarding UI

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#64] opened 2016-05-23 21:04 UTC
Per murally board info [here](https://app.mural.ly/t/bluemixdeveloperadvocates4089/m/bluemixdeveloperadvocates4089/1463564736871), create UI for demo onboarding process.

**Comment by benrondeau** [comment] 2016-05-23 21:05
@JakePeyser Does this issue need to be the current milestone, or do you think it should be pushed back?

**Comment by JakePeyser** [comment] 2016-05-23 21:31
I think this is a duplicate of #57 - User login will incorporate the demo onboarding scenario. Let me answer that question there.

**Comment by JakePeyser** [comment] 2016-05-23 21:34
I think the mockups detailed in #51 does, but implementation-wise I think barebones create session and log-in would be fine

**Comment by benrondeau** [comment] 2016-05-23 21:42
@JakePeyser So close this issue and just integrate this take into #57? That is where I think it belongs, as #51 deals with the map view only, per my understanding.

**Comment by JakePeyser** [comment] 2016-05-23 21:48
@benrondeau That is a good point. Maybe a separate issue is needed to contain design work for demo onboarding mockups

**Comment by benrondeau** [comment] 2016-05-23 21:53
@JakePeyser Yes. I also think #57 is too vague right now to know what it contains and doesn't. My reading is that it is the technical implementation of that component, but maybe you meant the whole enchilada. Can you maybe clarify what you wanted that task to entail?

**Comment by benrondeau** [comment] 2016-05-23 21:54
@JakePeyser I also vote for a 'design' label be added as we only have 'UX' right now which does not necessarily mean UI. Your thoughts?

**Comment by JakePeyser** [comment] 2016-05-23 21:59
It was intentionally vague b/c we didn't have the flow set just yet. I'll leave it up to you if you want it to encapsulate the whole demo onboarding UI or if you want to break it down into multiple issues.

Also, a `design` label sounds like a good idea. I'll add one

**Comment by JakePeyser** [comment] 2016-05-23 22:03
Actually, does the `visual` tag suffice @benrondeau? I forgot about that one - it should encapsulate UI work

**Comment by benrondeau** [comment] 2016-05-23 22:24
Ahh yes. Missed the `visual` tag. That should be good for now

**Comment by benrondeau** [comment] 2016-05-23 22:27
@JakePeyser I'd like to focus task #57 on the technical implementation and design into a separate task (this one). Hope that is okay.

**Comment by JakePeyser** [comment] 2016-05-23 22:28
Sounds good to me. Feel free to edit the description/names of the tasks to accommodate their new purpose

**Comment by benrondeau** [comment] 2016-05-24 21:27
Simple prototype created for this experience:

https://invis.io/9T7F6JOJE

@JakePeyser for your review

**Comment by JakePeyser** [comment] 2016-05-25 04:08
Awesome @benrondeau. The only change I would make is for the location selection for new retail store managers. We might have >100 locations, so dedicated buttons for each location probably wouldn't scale.

**Comment by benrondeau** [comment] 2016-05-25 19:38
Great point. Updated prototype to reflect this change.

**Comment by JakePeyser** [comment] 2016-06-02 04:44
Since we decided to nix the "Join Existing Session" button, this may need to be updated to reflect the updated Mural.ly designs.

**Comment by jakepeyser** [comment] 2016-07-14 22:03
@benrondeau are you satisfied with this design? It has been sitting here for awhile

**Comment by jakepeyser** [comment] 2016-08-03 13:50
@Austinauth is this issue still needed, or have you created a supplement(s)?

**Comment by Austinauth** [comment] 2016-08-04 14:42
@jakepeyser 

@kingtraceyj and I created a supplement issue [here](https://github.com/IBM-Bluemix/logistics-wizard/issues/148). I think we can safely close this one if you don't need it anymore.

**Closed** 2016-08-04 14:51 UTC
Labels: invalid
